include ~/.cache/wal/colors-kitty.conf
font_family family="SF Pro Mono"
font_size 14.0
clipboard_control write-clipboard write-primary read-clipboard read-primary
shell_integration enabled
term xterm-kitty
map_timeout 1.2
tab_title_template "{index}:{session_name} {title}"
enabled_layouts splits,tall,fat,grid,stack,horizontal,vertical
tab_switch_strategy previous
tab_bar_style powerline
cursor_trail 1
cursor_trail_start_threshold 1
cursor_trail_decay 0.01 0.20
cursor_beam_thickness 2.0
cursor_shape beam
confirm_os_window_close 0
hide_window_decorations yes
scrollback_lines 10000
enable_audio_bell no
bell_on_tab none
background_opacity 0.5
dynamic_background_opacity yes
background #000000
foreground #c1c1c1
selection_background #c1c1c1
selection_foreground #000000
url_color #999999
cursor #c1c1c1
active_border_color #333333
inactive_border_color #121212
active_tab_background #000000
active_tab_foreground #c1c1c1
inactive_tab_background #121212
inactive_tab_foreground #999999
tab_bar_background #121212
